# Generated by Django 5.1.4 on 2024-12-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_owner',
        ),
        migrations.AddField(
            model_name='project',
            name='project_owner_email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
